name: Build Spigot Plugin

on:
  push:
    paths:
      - "generate-plugin.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Read Plugin Request
        run: |
          command=$(jq -r '.command' generate-plugin.json)
          message=$(jq -r '.message' generate-plugin.json)
          echo "COMMAND_NAME=$command" >> $GITHUB_ENV
          echo "MESSAGE=$message" >> $GITHUB_ENV

      - name: Upload to GitHub Pages
        run: |
          mkdir -p docs/plugins
          touch docs/plugins/${{ env.COMMAND_NAME }}.jar  # Simulazione della creazione del file
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/plugins
          git commit -m "Aggiunto plugin ${{ env.COMMAND_NAME }}"
          git push
